### ISSUE TITLE
The width of Redshift GUI window outstretches 4x the legnth of my screen (1280x1024) 17in monitor

### ISSUE THREAD

**Issue by swiftidd** [maoserr/redshiftgui#10]
I recently downloaded RedShift GUI a few days after discovering f.lux and decided I like Redshift GUI better but have noticed a reoccurring annoyance with the width of it's GUI window.

When I click mid center on right side of GUI to adjust the width size it has tendency to flicker partially going off the screen if I release the window at that point it expands 4x the length of my screen which leaves me manually to drag and drop to rezise repeating till it's back to original size or to close the program and re-open resetting default window size.

My operating system is windows 7 service pack 1, I have noticed Redshift GUI is not compatible with Windows 7 'Windows Aero Snap feature' which if any open software or folder window is dragged to each corner it will resize. Redshift GUI doe's not do that which I think causes the behavior to expand width ways waaay off the screen

Thanks
![2013-05-29_23-08-19](https://f.cloud.github.com/assets/4564200/581942/a7135708-c8ac-11e2-94e7-92ec2a7db37a.jpg)

**Comment by yukulele** [comment]
I have the same problem on Ubuntu.

The window sometimes becomes very wide:
![Screenshot_20200108_103418](https://user-images.githubusercontent.com/347244/71966768-7e639400-3202-11ea-8205-73e4f259ee26.png)

It seems to happen often after resizing the setting window and saving.

**Comment by yukulele** [comment]
https://github.com/maoserr/redshiftgui/issues/21
