### ISSUE TITLE
Error: the package is of bad quality

### ISSUE THREAD

**Issue by avocadoelgatotaco** [maoserr/redshiftgui#12]
I try to install redshiftGUI-0.2.1-Linux-x86_64.deb and get (-)package is of bad quality
Lintian check results for /home/kevin/Downloads/RedshiftGUI-0.2.1-Linux-x86_64.deb:
Can't use an undefined value as an ARRAY reference at /usr/share/perl5/Lintian/Collect/Package.pm line 513, <$_[...]> line 15.
warning: collect info scripts about package redshiftgui failed
warning: skipping check of binary package redshiftgui
Can't use an undefined value as an ARRAY reference at /usr/share/perl5/Lintian/Collect/Package.pm line 513, <$_[...]> line 15.
warning: collect info md5sums about package redshiftgui failed
warning: skipping check of binary package redshiftgui
Can't use an undefined value as an ARRAY reference at /usr/share/perl5/Lintian/Collect/Package.pm line 513, <$_[...]> line 15.
warning: collect info file-info about package redshiftgui failed
warning: skipping check of binary package redshiftgui

**Comment by CavemanNinja** [comment]
+1 issue present in 0.2.1.
issue resolved in 0.2.4.
