### ISSUE TITLE
restoring after minimization resizes app window

### ISSUE THREAD

**Issue by welltell** [maoserr/redshiftgui#15]
After I click minimize window, and then restore it, the window is sooooo so so so WIDE! at least 5x as my screen. Happen on Windows 7, graphics Intel 945 GM.

**Comment by TetraSky** [comment]
This application is clearly not getting any new update. I suggest giving sunsetscreen a try
http://www.skytopia.com/software/sunsetscreen/
has most if not all features of Redshift, except it actually works.

**Comment by welltell** [comment]
Well, interesting app. I'll give it a try. At first sight it seems pretty good.

**Comment by welltell** [comment]
Thank you for your suggestion. I use the Sunsetscreen since you 
suggested it and I must say it really works! The only thing which could 
be somewhat better is the check whether the screen is really at adjusted 
colours. Minimum is 1 second but on my laptop it sometimes take even 
more seconds, and if I am suited for low level of light or even a dark 
condition, then this shock taking a few seconds isn't a pleasure. Thank 
you anyway, I like it!

Dne 27.7.2015 v 6:26 TetraSky napsal(a):

**Comment by albertaparicio** [comment]
Hi everyone!

This bug appears also on my desktop.

I'm running Linux Mint 17.3 x64 with Cinnamon 2.8.8

**Comment by fractalf** [comment]
+1 on Linux Mint 18
..but this project looks abandoned
