### ISSUE TITLE
Error on Launch: % 09:28 PM:[_parse_options] Invalid/empty config: /home/$USER/.redshiftgrc

### ISSUE THREAD

**Issue by stef204** [maoserr/redshiftgui#18]
Just installed this package on `Linux 4.7.2 x86_64`.

When no $HOME/.redshiftgrc is present, I can start program and then configure it, as to location, etc., and then save.  At that point, all is fine.

However, if I then kill it, next start gives following error, every time, no matter what IF there is a .redshiftgrc present:

```
% redshiftgui --min &!
% 09:47 PM:[opt_parse_map] Map empty.
```

The only way to temporarily fix is to delete .redshiftgrc and redshiftgui starts again.

Permissions on .redshiftgrc are 600, but I tried to loosen this up to 644, etc., no change.

Am I doing something wrong or is this a bug?

**Comment by steanne** [comment]
i figured this out a few years ago, but haven't the skill to do anything other than work around it.  it's [writing an rc file it can't read](https://classicforum.manjaro.org/index.php?topic=17942.0).  generate it through the gui, then edit it manually to fix the wrong characters and never edit it through the gui again.

**Comment by stef204** [comment]
Thanks for the info.  I figured out back then I had to create and edit the rc file manually which I did.  And it's been running fine ever since.
This bug should be fixed though, it sounds like something trivial.

**Comment by kmvan** [comment]
how about `chown root:root ./.redshiftgrc` ?

**Comment by steanne** [comment]
no, this is not a permisisons error.  it's a problem with the actual file content.

**Comment by kmvan** [comment]
> no, this is not a permisisons error. it's a problem with the actual file content.

Change permissions after fixed content?

**Comment by steanne** [comment]
no. this is not a permissions error.

**Comment by kmvan** [comment]
I know, but this will prevent it from being written.

**Comment by steanne** [comment]
i would suggest making the file immutable with chattr if you want to keep it from being overwritten.
