### ISSUE TITLE
Crazy window resizing

### ISSUE THREAD

**Issue by ardika** [maoserr/redshiftgui#21]
firstly i like to thank you its a great project.....i don't know if another also experience this issue, everytime i adjust color horizontal slider manually, that the window always unexpectedly resized it width size far 
beyond screen limit... i still remember when i used it on ubuntu everything looks fine, but now when im using it in manjaro x64 xfce this problem exists...here's the gif

![screen0-2017-02-15_07 56 37](https://cloud.githubusercontent.com/assets/4718951/22956696/1ad91eca-f356-11e6-8e15-b49819b84996.gif)

**Comment by steanne** [comment]
i have that problem on my old lmde2 32-bit machine but not on my 64-bit manjaro xfce.  it only happens with mouse dragging: if i tab to a slider and adjust it with arrow keys, it never happens.

**Comment by ardika** [comment]
thanks @steanne for the answer, 

> it only happens with mouse dragging: if i tab to a slider and adjust it with arrow keys, it never happens.

well the problem existed even im using tab and arrow keys to adjust it manually (poor me) 
btw im trying to build it from source but with no success... and then i lost my interest using it anymore..



[redshift_adjust.sh.zip](https://github.com/maoserr/redshiftgui/files/779880/redshift_adjust.sh.zip)
eventually i decide to create my own script to adjust gamma correction (brightness) and color temperature so i could do it simply using keyboard shortcut.....the script based on redshift-adjust (https://github.com/maandree/redshift-adjust)... im modified it so i could make it functional to adjust brightness and auto startup as well.....


im attach the script in case someone interesting with it

**Comment by catb0t** [comment]
@ardika, this project isn't actively maintained anymore.
thanks for the report and the script, though!

This seems like an issue specific to LMDE and Xfce since I've never seen it on GNOME, Unity or Windows, but either way it's not going to be fixed here any time soon.

**Comment by maxjf1** [comment]
I have an simmilar problem, the window open too small

Using Ubuntu 

![image](https://user-images.githubusercontent.com/6114888/53295328-c7bc1800-37d7-11e9-877a-c391c2b353bf.png)

**Comment by murmax** [comment]
Same on Windows 10 on 4K monitor (nothing of that happened on 1920x1080 monitor before).
