### ISSUE TITLE
Holding a temperature adjustment slider for a few seconds produces GUI bug

### ISSUE THREAD

**Issue by drws** [maoserr/redshiftgui#24]
I'm using v0.2.4 from AUR on Arch with MATE and if I grab and hold the slider for color temperature adjustment with mouse cursor for around two seconds, the slider and the window border get enlarged to the right side well off the screen. After that the lower right buttons are not accessible anymore until the application is restarted.

Screenshot:

![image](https://user-images.githubusercontent.com/1191893/27841748-3b946414-6104-11e7-8d03-956bece24b93.png)

**Comment by catb0t** [comment]
This repository is not maintained as you can tell. You can fork it and fix the issues yourself, however.

**Comment by drws** [comment]
Eh, I overlooked it. It's useful software despite this bug and it's still the most configurable of all the other redshift GUIs I found. I hope someone forks it in the future.
